### PR TITLE
Cloning revert.

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
## About The Pull Request
Adds cloning back into the game

## Why It's Good For The Game

Wounds are very lethal, surgery is slow. Surgery AND needing genetics if you ever get gibbed = nobody will ever come back from getting gibbed. Move to science techweb only if buc's genetics touches on this and makes it better.

## Changelog
:cl:
add: Cloning is BACK!
/:cl:

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
from the get go i will say i require some changes to cloning coming back. I want some kind of resource being used, be it some kind of scarce resource obtainable from cargo, or growable from botany, or having to be fuelled directly from the sm, or (my favourite idea) would be to require a fuck ton of synthflesh. Besides that i want cloning times to be extended for t2 and t3 parts.

**Comment by karmaisblackandbluepilled** [comment]
unfortunately I don't know how to do any of those things

**Comment by JinGiant** [comment]
> unfortunately I don't know how to do any of those things

Learn 2 code, there are plenty of people here that would help you

**Comment by TheChosenEvilOne** [comment]
closing this as cloning will not be added as it was.

**Pull request closed without merging**
