### PR TITLE
A bunch of heretic fixes and improvements

### PR DESCRIPTION
**Pull request by Salex08**
## About The Pull Request
Merges following ports from tg:
https://github.com/tgstation/tgstation/pull/60688
https://github.com/tgstation/tgstation/pull/60908
https://github.com/tgstation/tgstation/pull/61107
https://github.com/tgstation/tgstation/pull/63793
https://github.com/tgstation/tgstation/pull/64699
closes:https://github.com/The-Merchants-Guild/Merchant-Station-13/issues/273

## Why It's Good For The Game
More fixes and a heretic tgui antag panel

## Changelog
:cl: @MrMelbert @ViktorKoL @Watermelon914 @GoblinBackwards
fix: Rust Heretics now need to stand on Rust to heal again, instead of passive free healing
fix: corrected Fiery Rebirth's and Curse of Corrosion's heretic research descriptions
fix: fixed heretic research progression after unlocking the Lonely Ritual
qol: Heretic now has an antagonist panel
fix: Rust heretic ascension spread rusts everywhere again.
fix: Ash mark now deals the correct amount of damage and no longer gets stuck bouncing between the same two targets.
balance: Ash mark is significantly stronger due to this fix.
/:cl:

### CODE REVIEW

**Comment by Bomk16** [comment]
Whilst this is gaming, if you could port fully on new heretic noncaneralias has a 50 dollar code bounty on for it

**Comment by Salex08** [comment]
> Whilst this is gaming, if you could port fully on new heretic noncaneralias has a 50 dollar code bounty on for it

yeah I would actually like to port it if no one is on it

**Comment by Bomk16** [comment]
> > Whilst this is gaming, if you could port fully on new heretic noncaneralias has a 50 dollar code bounty on for it
> 
> yeah I would actually like to port it if no one is on it

I’d assume not since no one has said anything about it, make sure to tell alias about it so he can arrange payment if you do decide to pick it up

**Comment by NonCoderAlias** [comment]
Code my fucking bounty please, high on copium that noone has stolen code for fifty burger dollars by now (bounty is open still)

**Comment by Bomk16** [comment]
> Code my fucking bounty please, high on copium that noone has stolen code for fifty burger dollars by now (bounty is open still)

He truly has a way with wordw

**Comment by NonCoderAlias** [comment]
Code my bounty

**Comment by Bomk16** [comment]
> Code my bounty
It takes a bit to code you tard

**Comment by Salex08** [comment]
> Code my bounty

im on it

**Comment by Bucovineanu** [comment]
Just for me to be clear 100%, is this PR finished and ready for merge or is it gonna go through more iterations as per the previous commits?

**Comment by Salex08** [comment]
> Just for me to be clear 100%, is this PR finished and ready for merge or is it gonna go through more iterations as per the previous commits?

it would be good if you merged it now, I was thinking of closing the PR once I was finished and just readding it into the PR im currently working on

**Pull request closed without merging**
