### PR TITLE
Revert "Removes degeneracy."

### PR DESCRIPTION
**Pull request by Redrover1760**
## About The Pull Request

Reverts The-Merchants-Guild/Merchant-Station-13#25

## Why It's Good For The Game

There is no reason for non-binary people to not be in the game. Nor does non-binary being in the game negatively impact the experience at all, and added diversity is always good, when it's not some fetish shit. Especially when I know a few non-binary people myself.

## Changelog

:cl:
add: Non-binary people apparently actually do exist. Breaking News from NT headquarters.
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
Who are you? Why are you here? Go home!

**Comment by EtraIV** [comment]
> There is no reason for non-binary people to not be in the game. 

you're a /tg/ player, aren't you? surely removal of unnecessary shit should be fine with you

**Comment by Redrover1760** [comment]
> > There is no reason for non-binary people to not be in the game.
> 
> you're a /tg/ player, aren't you? surely removal of unnecessary shit should be fine with you

Huh? I thought the whole point of Merchant station was to re-add fun to the game? While I play tg, I do disagree with a lot of the more recent removals, especially of fun stuff.

I don't see how you can call the non-binary gender unnecessary shit. Sure, it is optional, but at the same time I see zero counterarguments for why it should be removed.

**Comment by EtraIV** [comment]
> > > There is no reason for non-binary people to not be in the game.
> > 
> > 
> > you're a /tg/ player, aren't you? surely removal of unnecessary shit should be fine with you
> 
> Huh? I thought the whole point of Merchant station was to re-add fun to the game? While I play tg, I do disagree with a lot of the more recent removals, especially of fun stuff.
> 
> I don't see how you can call the non-binary gender unnecessary shit. Sure, it is optional, but at the same time I see zero counterarguments for why it should be removed.

how are they/them pronouns fun

**Comment by Redrover1760** [comment]
> > > > There is no reason for non-binary people to not be in the game.
> > > 
> > > 
> > > you're a /tg/ player, aren't you? surely removal of unnecessary shit should be fine with you
> > 
> > 
> > Huh? I thought the whole point of Merchant station was to re-add fun to the game? While I play tg, I do disagree with a lot of the more recent removals, especially of fun stuff.
> > I don't see how you can call the non-binary gender unnecessary shit. Sure, it is optional, but at the same time I see zero counterarguments for why it should be removed.
> 
> how are they/them pronouns fun

They let you have fun increasing the roleplaying aspect and customization options of your character. For instance, a person could want to play and roleplay as a lizard. Real people are non-binary (one of my best friends is to note) and letting people be comfortable selecting their own gender will improve the experience. It is essentially like removing clothing from the game because it exists. Sure, most people won't care and don't really care about their looks (too busy interacting with other aspects of the game), but the people who do want to dress up have less fun due to have less options. Everyone in this game makes a character, and by removing character creation options, there is less fun to have in that. Sure, sometimes you have to remove stuff due to real valid reasons (I.e cats), but I don't see how non-binary fits those qualifications.

**Comment by TheChosenEvilOne** [comment]
lol

**Comment by MACIEKBAKI** [comment]
>lrp
>roleplay
???

**Comment by Redrover1760** [comment]
> > lrp
> 
> > roleplay
> 
> ???

LRP is not NRP. Roleplay exists in LRP, but the priority is mechanics, and for roleplaying to not get in the way of mechanical based fun stuff.

**Comment by OceanFish1** [comment]
What the fuck am I witnessing in comment section?
Good thing the pr's closed

**Pull request closed without merging**
