### PR TITLE
Adds MiniStation

### PR DESCRIPTION
**Pull request by hamurlik**
Here's the map in it's full glory as of the latest commit.
## About The Pull Request
Adds MiniStation. Originally for hippie station, then ported to vmstation, then shamelessly stolen by me.

## Why It's Good For The Game
Normal stations, on lowpop, are very empty and player interaction is unlikely. This adds a station designed specifically for lowpop, much smaller compared to a normal station, while having most of the features.

## Changelog
:cl: giacom, johntheautist, hamurlik.
add: ministation
/:cl:

TCEO EDIT:
[TEST MERGE CONFIG PATCH](https://github.com/The-Merchants-Guild/Merchant-Station-13/files/8402094/TESTMERGE.txt)
don't edit this, thanks. used for automatic config patching.

### CODE REVIEW

**Comment by trollertroll** [comment]
> > TEG as primary engine
> 
> based
> 
> I'd also say solars and a small permabrig are kinda needed at times. Don't forget that genetics is in science now. About the AI sat, what's the room at the far right?

Gravity generator

**Comment by trollertroll** [comment]
> Don't forget that genetics is in science now.

Moved genetics to science.
genetics2

Expanded virology.
virology2

**Comment by trollertroll** [comment]
turns out atmos is not fixed. fucking smart pipes

**Comment by trollertroll** [comment]
image
new tiny tiny tiny tiny permabrig. it can be escaped by throwing the stool at vending machines, that will give ingredients for a spear. break the window with the spear and fly to the nearest airlock.

**Comment by trollertroll** [comment]
i am not even going to try to make atmos work with smart pipes. ill work on other shit until someone finally reverts it

**Comment by EdgeLordExe** [comment]
my main issue with this map is really shitty maint, feel free to add some interesting roooms to it

**Comment by trollertroll** [comment]
Here's how the map looks like right now

I am working on solars now

**Comment by trollertroll** [comment]
image
image
image
image

**Comment by trollertroll** [comment]
image
maint curator office. the floor is actually runed, but it doesnt show as such in strongdmm

**Comment by trollertroll** [comment]
Map's fully playable now. Needs playtesting to fix bugs, and I am not going to play fucking singleplayer ss13. Ready for merging

**Comment by EdgeLordExe** [comment]
ok im working on feedback this looks really good but i have some requests before i merge this /testmere this

**Comment by EdgeLordExe** [comment]
ok so there is not enough maint
we really like big maint.
there also doesnt seem to be ai sat, please add those 2 before i merge this

**Comment by TheChosenEvilOne** [comment]
> ok so there is not enough maint we really like big maint. there also doesnt seem to be ai sat, please add those 2 before i merge this

AI is in tcommsat.

**Comment by TheChosenEvilOne** [comment]
this has some roundstart active turfs
image
image
image
image
image
image

**Comment by TheChosenEvilOne** [comment]
the solars are WAY too big for this sized map.

**Comment by trollertroll** [comment]
> the solars are WAY too big for this sized map, this map currently has 144 solar panels compared to Meta with 141 solar panels mapped in. (though kilo has 224(!!) solar panels)

I wasted 4 days of my life in strongdmm glued to the screen, you fix this shit yourself

**Comment by TheChosenEvilOne** [comment]
> > the solars are WAY too big for this sized map, this map currently has 144 solar panels compared to Meta with 141 solar panels mapped in. (though kilo has 224(!!) solar panels)
> 
> I wasted 4 days of my life in strongdmm glued to the screen, you fix this shit yourself

ok

**Comment by not-a-furry** [comment]
y'all done can i test it?

**Comment by TheChosenEvilOne** [comment]
> y'all done can i test it?

it had a lot of issues that were noticed during the five minutes it was played for

**Comment by Bucovineanu** [comment]
No telecomms, add telecomms

**Comment by TheChosenEvilOne** [comment]
this is going to need changes now that #87 is merged.

**Comment by trollertroll** [comment]
It's been 20 days but I don't give a shit, I'm gonna fix this shit once and for all

I already fixed comms, I just need to do the atmos from scratch

**Comment by trollertroll** [comment]
Fuck you, it's playable now. I already tested it and it fucking werks

**Comment by karmaisblackandbluepilled** [comment]
did you add the plant manipulator to botany

**Comment by trollertroll** [comment]
> did you add the plant manipulator to botany

wtf are you talking about

**Comment by karmaisblackandbluepilled** [comment]
the plant gene manipulator retard

**Comment by trollertroll** [comment]
fuck you

**Comment by trollertroll** [comment]
alright black thugs, merge this shit, is all fixed, everything works, yes, even comms, even atmos, please merge this shit im begging you please please

**Comment by QuakeIV** [comment]
this looks ok to me ill poke the other dudes

**Pull request closed without merging**
