### PR TITLE
Pipe Bomb

### PR DESCRIPTION
**Pull request by nicholast013**
unknown

## About The Pull Request

This PR added new improvised explosive named pipe bomb its commonly used for terrorizing certain people.

## Why It's Good For The Game

Making hos and security shit their pants

## Changelog
:cl:
add: Added pipe bomb and recipe for pipe bomb
/:cl:

### CODE REVIEW

**Comment by nicholast013** [comment]
I WILL ADD MORE FEATURE!!

**Comment by nicholast013** [comment]
Signaller support has been added for pipe bomb

**Comment by nicholast013** [comment]
Need ideas

**Comment by QuakeIV** [comment]
code wise this more or less looks OK to me, it might need balancing though

can you post a video of using it

**Comment by nicholast013** [comment]
Alright

**Comment by QuakeIV** [comment]
also squash your commits holy shit

**Comment by karmaisblackandbluepilled** [comment]
Don't they get automatically squashed when merged with the server

**Comment by QuakeIV** [comment]
that does appear to be an option for merging actually, interesting

would still prefer a not-poop commit message

**Comment by karmaisblackandbluepilled** [comment]
Don't look at the dogshit that was committed before then lol

**Comment by nicholast013** [comment]
Yes

**Comment by QuakeIV** [comment]
anyways show me it working and ill merge

**Comment by QuakeIV** [comment]
show a screenshot of new fuse color?

**Comment by nicholast013** [comment]
Capture

**Comment by QuakeIV** [comment]
ah OK so no huge difference

**Comment by nicholast013** [comment]
but it make sense why there are fire

**Comment by QuakeIV** [comment]
merged manually, closing PR

**Pull request closed without merging**
