### PR TITLE
Removes degeneracy.

### PR DESCRIPTION
**Pull request by AcapitalA**
Removes the non-binary option, IDpol and neurotypicals have no place in a 2D spaceman game where you beat eachother in the head with toolboxes.

### CODE REVIEW

**Comment by Jeff-Dome** [comment]
I can't wait for some brain dead retard on reddit to make a shitty post about this PR and some how call it the nazis of SS13

**Comment by TheChosenEvilOne** [comment]
fuck it, what is the worst that could happen.

**Comment by optimumtact** [comment]
fragile lmao

**Comment by TheChosenEvilOne** [comment]
@optimumtact hi oranges

**Pull request merged**
