### PR TITLE
Ports reworked cockcult from beestation

### PR DESCRIPTION
**Pull request by TymurShatillo**
## About The Pull Request

Cockcult was a cool thing, through it had many issues, it had many fun and unique mechanics, and, sadly, was fucked by tg "remove, not improve" policy. This PR ports the reworked version of this gamemode(as a dynamic ruleset) from BeeStation, because it is better then the original version and more fun to play.

Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2124

Opened as a draft for discussion

## Why It's Good For The Game

A cult with many cool and unique mechanics

## Changelog
:cl: SuperSlayer
add: Ports reworked cockcult from beestation
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Played it on bee! It's great.

**Comment by karmaisblackandbluepilled** [comment]
-1, the bee clock cult is dogshit and I am already working on porting yog's cult.

**Comment by TymurShatillo** [comment]
> -1, the bee clock cult is dogshit and I am already working on porting yog's cult.

I can say as yog former player/coder that bee cult is better, because on yogstation it is like locked 30-40 minutes of cool gameplay(and then your cult goes wiped by a tide of armed dudes with guns and mechs), and on bee it isn't locked to game time and instead the moment when the final stand will start depends on how did cultists play and can be longer then on yogstation. And also it has better progression mechanics, so i think that it is better.

**Comment by karmaisblackandbluepilled** [comment]
And I can say that as a former hippie player/coder(yog ported it from hippie) that if the cult players don't suck they just get weapons from the station and maze up reebe with alloy walls and turrets to prevent mechs/guns from instantly raping the entire cult.

**Comment by TymurShatillo** [comment]
Hmmmm

**Comment by TymurShatillo** [comment]
Ok then, i will maybe wait untill it will be more understandable what clockcult version will players prefer

**Comment by TymurShatillo** [comment]
Actually, fuck bee cockcult

**Pull request closed without merging**
