### PR TITLE
Ports bloodsuckers

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

https://github.com/yogstation13/Yogstation/pull/13273

This is kinda a port of a port, but who cares. Bloodsuckers are antagonists with many cool mechanics, and they are fun to play so i think that porting them will be cool.

## Why It's Good For The Game

image

## Changelog
:cl: TheSwain, JohnFulpWillard, SuperSlayer
add: Bloodsucker antagonist
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Fuck

**Comment by JohnFulpWillard** [comment]
I know I have no say because open source, but I hate the fact that my antagonist that I spent months on is being ported to a racist hate server. 👎

**Comment by karmaisblackandbluepilled** [comment]
lol

**Comment by ChungusGamer666** [comment]
> I know I have no say because open source, but I hate the fact that my antagonist that I spent months on is being ported to a racist hate server. 👎

cope lol

**Comment by karmaisblackandbluepilled** [comment]
please never leave a comment here, your username is vomit inducing.

**Comment by ChungusGamer666** [comment]
big big chungus big chungus big chungus

**Comment by ghost** [comment]
> I know I have no say because open source, but I hate the fact that my antagonist that I spent months on is being ported to a racist hate server. 👎

Morbed

**Comment by ghost** [comment]
When testmerge

**Pull request closed without merging**
