### PR TITLE
 TGUI-based ERT spawning menu + Custom ERTs

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
## About The Pull Request

Entirely reworks the admin ERT spawning menu.
Draft for now so you can scream at my code and tell me where it's dogshit.

## Why It's Good For The Game

I get 50$, you get new and improved TGUI ERT spawning menu. Win-win.

## Changelog
:cl:
code: ERT code has been changed, check PR for details if you care.
admin: Entirely redone ERT spawning menu. New and improved. You can now choose to spawn an ERT with their pre-assigned mechs (i.e. a Deathsquad might spawn with Death Ripleys, Code Red ERT with marauders/seraphs, etc
/:cl:
TODO:
- [X] Make ERT spawning menu functional with current ERTs
- [x] Make ERT spawning menu more informative when it comes to mechs
- [x] Allow creation of custom ERTs
- [x] Potentially find stuff I need to do that I have not written in TODO:
- [x] Fix bugs
- [x] Finish

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
Currently a draft so you can scream at my bad coding decisions.

**Comment by MACIEKBAKI** [comment]
i hope you like long PRs, quake

**Comment by MACIEKBAKI** [comment]
ready 4 review, tell me how bad my code is. suggest changes, too.

**Comment by MACIEKBAKI** [comment]
the image in the PR description is outdated btw, I just don't feel like updating it right now but it gives you the right idea

**Comment by eLeCtrOssSnake** [comment]
holy fuck

**Comment by eLeCtrOssSnake** [comment]
I'd review this, but I am not quite experienced with tgui, so it better be reviewed by someone else.

**Comment by karmaisblackandbluepilled** [comment]
I think there's like two people here who actually know tgui and one of them said he hates it.

**Comment by eLeCtrOssSnake** [comment]
ahahahaha

**Comment by eLeCtrOssSnake** [comment]
testmerge ready yes. merging to master.

**Comment by MACIEKBAKI** [comment]
"Testmerge ready"
less than 10 minutes later
*Merged to master*

**Comment by Bucovineanu** [comment]
Problem?

**Pull request merged**
