### PR TITLE
Xray, forum to discord, superfart in crit, thermals revert, e-gun no longer bulky

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
You can make the XRAY mutation again.
Replaced a forum hyperlink to a discord one, add it to the config.
You can sfart in crit(intended)
Thermals are no longer an activatable spell but they are as before.
E-Guns are no longer bulky what the fuck was that change KILL yourself

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
fill out the pr body dear god

**Comment by EdgeLordExe** [comment]
if 2 years down the road i have to lookup this exact fucking pr and see that it has absolutely no comment attached to it besides the title, i'd fucking an hero myself holy shit

**Comment by TheChosenEvilOne** [comment]
watch this

**Comment by EdgeLordExe** [comment]
> watch this

if you merge this without waiting till he adds a comment to the pr body i swear to fucking god, i will strangle you

**Comment by TheChosenEvilOne** [comment]
> > watch this
> 
> if you merge this without waiting till he adds a comment to the pr body i swear to fucking god, i will strangle you

no, I just labeled it

**Comment by karmaisblackandbluepilled** [comment]
> fill out the pr body dear god

ok

**Comment by TheChosenEvilOne** [comment]
@EdgeLordExe image

**Comment by EdgeLordExe** [comment]
merging

**Pull request merged**
