### PR TITLE
Removes ALL the delay on deconstruction and constructing stuff with tools(except for welding through walls).

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
Why is this good for the game? We aren't an hrp larp shit poop server, we put up movespeed AND action speed. Game faster = good. Plus waiting sucks.
Kept welding because otherwise speedrunning the AI core could be doable.

## Changelog
:cl:
balance: Nanotrasen finally added the muscle upgrades that lets all of the crewmembers use tools faster! Not welding tools though.
/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
what the fuck is that commit

**Comment by karmaisblackandbluepilled** [comment]
haha get it it's acapital, your name, and pussy, a cat! isn't it funny!
Merge my pr or you're next.

**Comment by TheChosenEvilOne** [comment]
h

**Comment by karmaisblackandbluepilled** [comment]
Merge.

**Comment by Bucovineanu** [comment]
average justice PR be like 2837 files changed, one mechanic changed, tg reverted to death (good), nonsensical commit names.

Seems fine, merged

**Pull request merged**
