### PR TITLE
Add plastic pots

### PR DESCRIPTION
**Pull request by eLeCtrOssSnake**
## About The Pull Request
Adds plastic pots which allow planting in different areas.
Can be made with 5 plastic sheets. Needs sand/sandstone for soil to grow plants.

## Why It's Good For The Game
Allows botanists to give various plants to other departments. Engages more department interaction.

## Changelog
:cl:
add: Added craftable plastic pots
imageadd: Added plastic pot sprite
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
This is how plastic pot with nettles planted looks:
image

**Comment by QuakeIV** [comment]
sandstone is hard to get a hold of on the station, you might consider filling these up via composting instead

from code/modules/hydroponics/hydroponics.dm
if(IS_EDIBLE(reagent_source) || istype(reagent_source, /obj/item/reagent_containers/pill))
			visi_msg="[user] composts [reagent_source], spreading it through [target]"
			transfer_amount = reagent_source.reagents.total_volume
			SEND_SIGNAL(reagent_source, COMSIG_ITEM_ON_COMPOSTED, user)

**Comment by eLeCtrOssSnake** [comment]
I mean sand/sandstone is botany origin anyway. But I've also thought about composting as a soil filler. It can be both too.

**Comment by QuakeIV** [comment]
ah fair, i thought you had to pester miners to get it

**Comment by eLeCtrOssSnake** [comment]
I'd say merge it now, and when I'll rework botany I will also add second soil filler.

**Pull request merged**
