### PR TITLE
Changes hypospray sprite

### PR DESCRIPTION
**Pull request by EdgeLordExe**
## About The Pull Request

New sprote look good

## Changelog
:cl:
add: Changed hypospray sprite
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
post a pic of it retard

**Comment by TheChosenEvilOne** [comment]
sovl: destroyed

**Comment by JinGiant** [comment]
I am phoneposting and cannot see the sprite, post it immediately or I will revert this pr!

**Comment by TheChosenEvilOne** [comment]
> I am phoneposting and cannot see the sprite, post it immediately or I will revert this pr!

user issue

**Pull request merged**
