### PR TITLE
"Everyone" now have maintenance access

### PR DESCRIPTION
**Pull request by SoftStone101**
## About The Pull Request

Grants maintenance access to crew members with the expection of prisoners.

## Why It's Good For The Game

Everyday plasma-fires, hull breaches, bombs and more take the lives of crew members just because they couldn't seek shelter in maintenance

seriously this is very annoying

## Changelog
:cl:
balance: Crewmembers have maintenance access
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
no

**Comment by Bomk16** [comment]
Not a bad idea tbh since alot of roles would benefit from it

**Comment by karmaisblackandbluepilled** [comment]
no

**Comment by Bomk16** [comment]
> no

Stay mad :troll:

**Comment by NonCoderAlias** [comment]
That's greyman's land, unholy grounds. -1

**Comment by Bucovineanu** [comment]
People already have maintenance access from their departments and the heads of staff and/or AI can set emergency maintenance access that makes this PR irrelevant in the first place. -1 with prejudice.

**Comment by EtraIV** [comment]
Standing with Buco on this one.

> Everyday plasma-fires, hull breaches, bombs and more take the lives of crew members just because they couldn't seek shelter in maintenance

That's what emergency access is for, like he said.

**Comment by EtraIV** [comment]
Well that's 4 of our admins shouting this down, God damn. Going to close then.

**Pull request closed without merging**
