### PR TITLE
Makes Null_crates cheaper by a factor of three

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
basnnga

## Changelog
:cl:
balance: Nullcrate production is in FULL swing. They are way easier to get now!
/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
mfw mfw

**Comment by KangTut** [comment]
This is stupid. You can flood the station with nulls with syndi money already.

**Comment by karmaisblackandbluepilled** [comment]
With syndie matter you reach a critical mass of items no matter what. This is for the cargo subhumans after they steal an emag from a murderbone esword emag syndie.

**Comment by KangTut** [comment]
Lowering the price will make the critical mass even more critical. Sell plasma and do bounties. You shouldn't make it easier to flood the station with dangerous items because you can't be bothered to earn money especially when there are talks of giving cargo more ways to make money.

**Comment by karmaisblackandbluepilled** [comment]
>there are talks of giving cargo more ways of making money
Where? Up your ass?

**Comment by KangTut** [comment]
Speak for yourself have you not heard of the crypto mining talks? You're trying to make these cheaper than some gun crates.

**Comment by joookschad** [comment]
bring back stock trading

**Comment by EtraIV** [comment]
> Speak for yourself have you not heard of the crypto mining talks? You're trying to make these cheaper than some gun crates.

you are high off your ass, literally no discussion about this in any PR or on discord

**Pull request merged**
