### PR TITLE
Hunter demon antag

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

It is a port of my yog PR with a new antag - https://github.com/yogstation13/Yogstation/pull/14191

This antagonist is something like a slaughter demon but less murderbone and with a shittone of mechanics. Check the original PR please for more information.

## Why It's Good For The Game

New antagonist

## Changelog
:cl: SuperSlayer
add: Hunter demon antagonist
imageadd: Blood orb sprites
imageadd: Hunter demon actions sprites
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
Fix the issues and we'll do a test merge, this looks interesting.

**Comment by TymurShatillo** [comment]
I will fix them tomorow

**Comment by TymurShatillo** [comment]
Wtf, linters fail why other checks are sucessfull, how should i fucking understand what is wrong

**Comment by TymurShatillo** [comment]
Bruh

**Pull request closed without merging**
