### PR TITLE
Adds the smug emote and flags to OOC, fucks with CI

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
Adds the smug emote. Don't do it too much or you will bite your tongue off!
dreamseeker_o1fSQIAPRG

Animated, naturally.
Taken from old hippie, thank you dwarf.

Also adds the flags to ooc, thank you turret for the code.
Removes the Unmanaged Global Var check from CI, fuck you.
## Changelog
:cl:
add: Added the *smug emote.
add: Added flags to your ooc names.
/:cl:

### CODE REVIEW

**Comment by SireTurret2** [comment]
CURB YOUR ENTHUSIASM

**Comment by karmaisblackandbluepilled** [comment]
it goes over lights now, fixed that bug

**Comment by JinGiant** [comment]
Gay ass animated emote, what's next, animated sex scene when I type *sex???

**Comment by karmaisblackandbluepilled** [comment]
my favorite part of this is that edge literally did not read
a. The title of the PR.
b. The content of the PR.
c. The code changes.
He just merged.

**Pull request merged**
