### PR TITLE
Adds simpson skintone

### PR DESCRIPTION
**Pull request by trollertroll**
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".
image

:cl:
add: Well well, Look at the city slicker pulling up in his fancy German car
/:cl:

### CODE REVIEW

**Comment by cuckooman** [comment]
amazing

**Comment by karmaisblackandbluepilled** [comment]
+1 if this works lol

**Comment by trollertroll** [comment]
> +1 if this works lol

I assure you it does, I tested it on a local server

**Comment by EtraIV** [comment]
> +1 if this works lol

it changes 5 lines of code, what do you mean "if it works"

**Comment by karmaisblackandbluepilled** [comment]
> > +1 if this works lol
> 
> it changes 5 lines of code, what do you mean "if it works"

you think I spend my time reading code from a dude named trollertroll?

**Comment by EtraIV** [comment]
Add it to the rotation of `/datum/reagent/spraytan/expose_mob` in `/code/modules/reagents/chemistry/reagents/other_reagents.dm` and I'll merge it

**Pull request merged**
