### PR TITLE
Removes families, replaces them with Yog gangs

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR removes families, and replaces them with gangs. Gangs are cool, families are not.

Main PR:
https://github.com/yogstation13/Yogstation/pull/4661

Also included:
https://github.com/yogstation13/Yogstation/pull/5118
https://github.com/yogstation13/Yogstation/pull/8415
https://github.com/yogstation13/Yogstation/pull/8807

Optional stuff(Maybe will port, maybe not):
https://github.com/yogstation13/Yogstation/pull/10665

## Why It's Good For The Game

Families are cringe MRP antag and old gangs are cool and based 

## Changelog
:cl: SuperSlayer
add: Ported gangs from yogstation
del: Removed families
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
let me ask the other admins, I support this personally

**Comment by TymurShatillo** [comment]
> let me ask the other admins, I support this personally

Ok

**Comment by EtraIV** [comment]
a cooder after your own heart, eh @karmaisblackandbluepilled 
image

**Comment by karmaisblackandbluepilled** [comment]
trve...

**Pull request closed without merging**
