### PR TITLE
wiremod proximity pinpointer

### PR DESCRIPTION
**Pull request by SNIAPA**
## About The Pull Request
added proximity pinpointer component that returns xyz co-ordinates of a entity

## Why It's Good For The Game
we finnaly can use pathfinding component

## Changelog
:cl:
add: proximity pinpointer
/:cl:

### CODE REVIEW

**Comment by EtraIV** [comment]
god fucking damn dude quit the weed
changelogs are generated automatically as well, you cant just leave the defaults in

**Comment by karmaisblackandbluepilled** [comment]
how much did you test this in-game

**Comment by SNIAPA** [comment]
uh turns out i am a shitter and when i was cleaning up code i fucked and was too lazy to test so ima close this pr  and make another when i finish porting rest of the components

**Comment by MACIEKBAKI** [comment]
testing? who needs testing?

**Pull request closed without merging**
