### PR TITLE
Tesla explodes again

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
self-explanatory
## Changelog
:cl:
fix: The Tesla is a thing to fear again.
/:cl:

### CODE REVIEW

**Comment by xDyouGamer** [comment]
Based pr but wouldnt this cause the server to shit itself like it usually does from the exploding tesla?

**Comment by karmaisblackandbluepilled** [comment]
small price to pay for poopfart

**Comment by xDyouGamer** [comment]
True,speedmerge this bih

**Comment by schwaaaa** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
Tesla was limited to a total of 3 extra energy balls before due to that number, for some reason. No clue why they did that if the tesla didn't explode anyway.
Lowering 1.25 to 1.02 just makes it so there can be way more balls before the energy_to_raise is too high and energy_to_lower kicks in.

**Pull request merged**
