### PR TITLE
[Bounty]Ports surgery sounds and UI from TG

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

image

This PR ports TG surgery sounds and UI(the bounty says about surgery HUD, but i didn't find anything on TG about surgery HUD, so maybe it is a mistake. If i am wrong leave me please a link to the HUD PR).

https://github.com/tgstation/tgstation/pull/65578
https://github.com/tgstation/tgstation/pull/64579

## Why It's Good For The Game

Because it is good

## Changelog
:cl:
add: Surgery UI
soundadd: Surgeries now have sounds for when finished/inititated/failed
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Fucking tgui

**Comment by SuperSlayer0** [comment]
Maybe ready, through i had a very bad time with fixing this weird shit

**Comment by karmaisblackandbluepilled** [comment]
image
wait no this CHANGES SURGERY TO BE FUCKING SIGNALS?
AAAAAAAAAAAAAAAAAAAAAAA
FUCK YOU SHOEFOOOOOOT

**Comment by SuperSlayer0** [comment]
What is bad in signals

**Comment by karmaisblackandbluepilled** [comment]
their entire existence

**Pull request closed without merging**
