### PR TITLE
The Half Life sound update

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
Full list of changes:
Stepping on plating.
Stepping on unplated metal tiles.
The tcomms hum.
All "buttons" in the game.
The vote sound(20% chance only though)
Doors and windoors.
Vending machine hum.

https://user-images.githubusercontent.com/54416597/173676622-88c45f2e-05af-403c-94e7-9aa10f4eb293.mp4

## Changelog
:cl:
add: Changed the sounds of a lot of things, such as walking on normal tiles, opening doors and pressing on buttons to be more classic.
add: Added a background hum to vending machines.
:cl:

### CODE REVIEW

**Comment by Bucovineanu** [comment]
I'm a little terrified.

**Comment by karmaisblackandbluepilled** [comment]
Sounds changed with a higher quality remaster of the old sounds sent to me by someone I forgot.
Either memager or etra.

**Comment by eeSPee** [comment]
Are these the new sounds that we hear right now?

Because they're still a bit too loud and need normalized (some sounds are way louder than they should be)

**Comment by eeSPee** [comment]
A lot of the footsteps and vending machines.

**Comment by karmaisblackandbluepilled** [comment]
Alright, gonna normalize them through audacity. It *seems* that you can't actually do it through the code, or it's just really shitty.

**Comment by Bucovineanu** [comment]
Having played with them for a while, some sound level issues notwithstanding I like the sounds. I think it's been testmerged long enough to make a poll and ask people if they like it so we can full merge it.

**Pull request merged**
