### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by EtraIV**
## About The Pull Request

Adds a code of conduct, inspired by [SQLite's Code of Ethics](https://sqlite.org/codeofethics.html). It's the current year, okay?

### CODE REVIEW

**Review by MisterBones2910 — COMMENTED** [review]
fugginkek

**Comment by Bucovineanu** [comment]
This code of conduct will work very well for our christian server, +1

**Review by MACIEKBAKI — APPROVED** [review]
A great addition to our christian peace-loving server.

**Comment by EtraIV** [comment]
cool

**Comment by EtraIV** [comment]
wew lad
image

**Pull request merged**
