### PR TITLE
Adds a new sprite for the stacker 

### PR DESCRIPTION
**Pull request by BettonnCZ**
## About The Pull Request
Adds a new sprite for the stacker

## Why It's Good For The Game
They look different now

## Changelog
:cl:
add: new sprite
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
you can drag and drop images/gifs into the box to upload them to the pr
show us how it looks.

**Comment by BettonnCZ** [comment]
> you can drag and drop images/gifs into the box to upload them to the pr show us how it looks.

On my phone, I'll get to it tomorrow

**Comment by TheChosenEvilOne** [comment]
image
we do have icon diff.

**Comment by BettonnCZ** [comment]
> image we do have icon diff.

Wdym

**Comment by TheChosenEvilOne** [comment]
> > image we do have icon diff.
> 
> Wdym

I am just saying that you can look at the icon changes by pressing this button:
image

**Comment by prvdn** [comment]
With this color It looks like an old PC facing opposide direction from me

**Comment by QuakeIV** [comment]
i mean this isnt terrible, any objections to merge?

**Pull request merged**
