### PR TITLE
Borg damage slowdown

### PR DESCRIPTION
**Pull request by KangTut**
## About The Pull Request
Take 2 borgs will suffer damage slowdown after taking severe damage just like carbons
## Why It's Good For The Game
Because shut up

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
-1 this sucks ass if you merge this I'm buffing borgs in other ways

**Comment by KangTut** [comment]
your tears sustain me silicuck

**Comment by AcapitalA** [comment]
S H I T 
H
I
T

**Comment by AcapitalA** [comment]
But seriously, fixing borgs isn't as easy as simply applying a slowdown nor will it work. The problem is more deep-rooted than that sadly.

**Comment by KangTut** [comment]
Right now you only have a few ways to secure a kill on a rogue borg. You either need to click it with a flash(good luck with this moves peed) or ion it which you only get 2 of those at round start and need warden or hos access. The only other option is the robotics console which needs either a roboticist or RD either of which have to even be willing to lock down or blow the borg. 

Damage slow down would at least cause the borg to put more thought into their encounters since now they can't fight until their last module is almost gone then zoom away, bolt themselves inside maint and weld because every station weapon aside from maybe ion does brute damage to them.

**Comment by AcapitalA** [comment]
That's the thing with borgs.
They're better than normal spacemen in so many ways aside from a few, and those few things absolutely hard counter the shit out of them. A single flash / ion hit / laser pointer / someone on the other side of the station with a console can shut them down in one go. Making them move slower and leaving it at that isn't gonna fix the core problem they (and everyone else) suffer from.

**Comment by KangTut** [comment]
I already stated why I feel those hard counters aren't as reliable. Sure if you have them and someone is willing to use them then the borg is screwed, although I did forget the laser pointer but those are only spawned with the lawyer and RD (maybe you can order some but why would you?)

I also hate the idea that borgs should just be an outright improvement over humans. They always felt like a punishment role and yet they get to be cancerous little shits a lot of the time and get away with little consequence because the people they piss off can beat them to near death only to have them zoom off without any regard for damage aside from a missing module or two.

People suffer from borgs for different reasons. Janitors, Engi and Mining, suffer because the un-upgraded borg is an improvement over them and can only become better as the round goes on, and peacekeepers exist only to be obnoxious assholes which torment all crew. The only borgs that aren't amazing is Service which is just bar rp the bot and Medical which is easily the most balanced of the line up and should be what all borgs are like.

If anything damage slow down would give even an unprepared crewmember a fighting chance against a borg assuming the spaceman doesn't get flashed and it would cut down on dumb shit like engi borgs being free to welderbomb whatever they don't like.

Borgs do need an overhaul and if this doesn't fit with what you guys have in mind then I'll close it.

**Comment by TheChosenEvilOne** [comment]
just remove em.

**Comment by Jeff-Dome** [comment]
Borgs were a Punishment role, like the clown. Then the mentally deranged decided to play as them normally then powergamers realised they can just be sec-borgs which means they're automatically better than sec

**Comment by TheChosenEvilOne** [comment]
I am okay with this getting merged, as the damage slowdown kicks in after receiving 40 damage. Ill merge this if @EdgeLordExe is okay with it (because I am biased against all silicons). Also @KangTut changelog.

**Comment by AcapitalA** [comment]
> Damage slowdown will just cause cyborgs to be unable to escape from anyone trying to kill them, especially on asimov. Killing them is one flash away anyway

This really. It's over if you get ioned / flashed because it's a literal old batong / taser with blindness included. Borgs suffer from cold combat still being applied to them on both ends. (stun arm lol)

**Comment by KangTut** [comment]
Sure borgs have some counters and I've already said why I don't think much of them but even then maybe I was being a little too harsh on them. 

And then I was made aware shortly after making this pr that you retards re-enabled sec borgs. Now I know that I was not harsh enough. Fuck borgs they deserve nothing but pain,

**Comment by TheChosenEvilOne** [comment]
> you retards re-enabled sec borgs.

merging rn

**Comment by TheChosenEvilOne** [comment]
fuck borgs, especially sec borgs.

**Pull request merged**
