### PR TITLE
[FINAL PR] Prepare the repo for a move to GitLab

### PR DESCRIPTION
**Pull request by EtraIV**
## About The Pull Request

This gets the repo ready for a seamless transition to a GitLab instance (probably [GitGud](https://gitgud.io/)), to keep the prying eyes of GitHub's moderators off our backs. Given how this commit breaks CI (I tried my best to avoid changing the existing CI configs, but in the end did have to alter one), this should probably be the last PR that is merged in this repo. Resolve as many other PRs as you can before going through with this.

## Changelog
:cl:
add: Overhaul GitLab CI scripts, now has full functionality of GitHub CI suite
config: Changed CI test server config for GitLab CI (BREAKS CI ON GITHUB!!!)
/:cl:

### CODE REVIEW

**Comment by EtraIV** [comment]
Huh. guess that didn't break github CI? Regardless, other PRs will need to be resolved or migrated manually by their authors across before this goes through.

**Comment by EtraIV** [comment]
@TheChosenEvilOne Since you're not on the Discord, this is something you specifically should be aware of: We're likely going to migrate the git repo to GitLab on Sunday (tomorrow). The link will probably be posted here once the move is done.

**Comment by EdgeLordExe** [comment]
you only live once

**Comment by karmaisblackandbluepilled** [comment]
hahahahahaha

**Pull request merged**
